# Generated by better-tg-cli's release workflow; do not edit by hand.
class BetterTgCli < Formula
  desc "Unofficial agent-friendly Telegram client for the command line"
  homepage "https://github.com/TheVilfer/better-tg-cli"
  version "0.23.1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/TheVilfer/better-tg-cli/releases/download/v0.23.1/better-tg-cli-0.23.1-darwin-arm64.tar.xz"
      sha256 "d4ba9753af746d081f6411ae8fc0b75dcda9f292c4de41b53de54fa04b416af5"
    end
    on_intel do
      url "https://github.com/TheVilfer/better-tg-cli/releases/download/v0.23.1/better-tg-cli-0.23.1-darwin-x64.tar.xz"
      sha256 "62b11dccbbd068a59ebddb2d675aad865585416e30eedeb094e590d85d0fd809"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/TheVilfer/better-tg-cli/releases/download/v0.23.1/better-tg-cli-0.23.1-linux-arm64.tar.xz"
      sha256 "aafc8f3137311d270784b512d5e09697ee6c6427eae9da67981ac6c95b8324ad"
    end
    on_intel do
      url "https://github.com/TheVilfer/better-tg-cli/releases/download/v0.23.1/better-tg-cli-0.23.1-linux-x64.tar.xz"
      sha256 "844259bfae1c713e166c9bd2d06557abcb99f0ec18642aa4fd183c03d8874b3f"
    end
  end

  def install
    bin.install "telegram"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/telegram --version")
    assert_match "read <chat>", shell_output("#{bin}/telegram help-all -g thread")
  end
end
