# Generated by better-tg-cli's release workflow; do not edit by hand.
class BetterTgCli < Formula
  desc "Unofficial agent-friendly Telegram client for the command line"
  homepage "https://github.com/TheVilfer/better-tg-cli"
  version "0.31.1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/TheVilfer/better-tg-cli/releases/download/v0.31.1/better-tg-cli-0.31.1-darwin-arm64.tar.xz"
      sha256 "2393938eef8e8d6097b552a6e82955c46e842bf37057e8176e7f28ccd687d195"
    end
    on_intel do
      url "https://github.com/TheVilfer/better-tg-cli/releases/download/v0.31.1/better-tg-cli-0.31.1-darwin-x64.tar.xz"
      sha256 "469cb7d89dec2958f21c86c5bc5726285ad819b4a3204276edd5efd28e94fe80"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/TheVilfer/better-tg-cli/releases/download/v0.31.1/better-tg-cli-0.31.1-linux-arm64.tar.xz"
      sha256 "54a822048a052d4afbec9bcc948a076c5368737746de34c24e71e8aaa2532d12"
    end
    on_intel do
      url "https://github.com/TheVilfer/better-tg-cli/releases/download/v0.31.1/better-tg-cli-0.31.1-linux-x64.tar.xz"
      sha256 "2a6bd725914a2791446df9c2e58f9351078fbf8c7c427b6f297b9346739c03b6"
    end
  end

  def install
    bin.install "telegram"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/telegram --version")
    assert_match "read <chat>", shell_output("#{bin}/telegram help-all -g thread")
  end
end
