# Generated by better-tg-cli's release workflow; do not edit by hand.
class BetterTgCli < Formula
  desc "Unofficial agent-friendly Telegram client for the command line"
  homepage "https://github.com/TheVilfer/better-tg-cli"
  version "0.19.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/TheVilfer/better-tg-cli/releases/download/v0.19.0/better-tg-cli-0.19.0-darwin-arm64.tar.xz"
      sha256 "7c281d54c5e4c431af74bddc2f9f5b7b420ab6a91a30775c344f1372ac958872"
    end
    on_intel do
      url "https://github.com/TheVilfer/better-tg-cli/releases/download/v0.19.0/better-tg-cli-0.19.0-darwin-x64.tar.xz"
      sha256 "937586214bebf4f6d735b816aca8c2d4e3e7291e622327d85ff687d4a9f56054"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/TheVilfer/better-tg-cli/releases/download/v0.19.0/better-tg-cli-0.19.0-linux-arm64.tar.xz"
      sha256 "34bc16998dbe3cf7880e3e2cb5dcb0e2fe568ad874ccdd239462a14370ddb0d7"
    end
    on_intel do
      url "https://github.com/TheVilfer/better-tg-cli/releases/download/v0.19.0/better-tg-cli-0.19.0-linux-x64.tar.xz"
      sha256 "1db90998a6fd50ae2da4d8929d15c692a2b3ba4e20093f9a0f8cbacadb56cfd5"
    end
  end

  def install
    bin.install "telegram"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/telegram --version")
    assert_match "read <chat>", shell_output("#{bin}/telegram help-all -g thread")
  end
end
